"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](purple)\
$os\
$username\
[](bg:bright-purple fg:purple)\
$directory\
[](fg:bright-purple bg:bright-red)\
$git_branch\
$git_status\
[](fg:bright-red bg:bright-blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$maven\
$nodejs\
$bun\
$nim\
$rust\
$scala\
[](fg:bright-blue bg:cyan)\
$docker_context\
[](fg:cyan bg:blue)\
$time\
[ ](fg:blue)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:purple fg:black"
style_root = "bg:purple fg:black"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:purple fg:black"
disabled = true # Disabled by default

[directory]
style = "bg:bright-purple fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:bright-red fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:bright-red fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[maven]
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:bright-blue fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue fg:black"
format = '[ ♥ $time ]($style)'
